# Generated by Django 5.0.7 on 2024-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_coursepurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Укажите город",
                max_length=50,
                null=True,
                verbose_name="Город",
            ),
        ),
    ]
